name: Build and Release Binaries

on:
  push:
    tags:
      - "v*" # Triggers on version tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }} binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: gitscribe
            asset_name: gitscribe-macos
          - os: ubuntu-latest
            artifact_name: gitscribe
            asset_name: gitscribe-linux
          - os: windows-latest
            artifact_name: gitscribe.exe
            asset_name: gitscribe-windows.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build binary with PyInstaller
        run: pyinstaller --onefile --name gitscribe cli.py

      - name: Rename binary for release
        shell: bash
        run: |
          mkdir -p release
          if [ "${{ runner.os }}" == "Windows" ]; then
            mv dist/gitscribe.exe release/${{ matrix.asset_name }}
          else
            mv dist/gitscribe release/${{ matrix.asset_name }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: release/${{ matrix.asset_name }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release in Public Repo
        uses: softprops/action-gh-release@v1
        with:
          repository: FayZ676/commit2content-releases
          token: ${{ secrets.RELEASES_REPO_TOKEN }}
          files: |
            artifacts/gitscribe-macos/gitscribe-macos
            artifacts/gitscribe-linux/gitscribe-linux
            artifacts/gitscribe-windows.exe/gitscribe-windows.exe
          draft: false
          prerelease: false
          generate_release_notes: false
          body: |
            ## Installation

            ### macOS
            ```bash
            curl -L https://github.com/FayZ676/commit2content-releases/releases/latest/download/gitscribe-macos -o /tmp/gitscribe && chmod +x /tmp/gitscribe && sudo mv /tmp/gitscribe /usr/local/bin/
            ```

            ### Linux
            ```bash
            curl -L https://github.com/FayZ676/commit2content-releases/releases/latest/download/gitscribe-linux -o /tmp/gitscribe && chmod +x /tmp/gitscribe && sudo mv /tmp/gitscribe /usr/local/bin/
            ```

            ### Windows (PowerShell)
            ```powershell
            Invoke-WebRequest -Uri "https://github.com/FayZ676/commit2content-releases/releases/latest/download/gitscribe-windows.exe" -OutFile "$env:USERPROFILE\gitscribe.exe"
            # Then add to PATH or move to a directory in PATH
            ```

            ### Manual Installation
            Download the appropriate binary for your platform from the assets below, make it executable, and move it to a directory in your PATH.

            ## Usage
            ```bash
            gitscribe content --help
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_REPO_TOKEN }}
